### PR TITLE
Feature: Increased the size of photo uploads from Resolution Selector Menu (Revamp #298)

### PR DESCRIPTION
**Pull request by null-nick**
## Description

Revamp increase size of photo uploads (#298) 

- [ ] Fix broken preview for photo 2560px (<a href="https://github.com/TGX-Android/Telegram-X/assets/64551534/64f27313-5835-4284-af96-33ed94ec1efb">Screenshot</a>)
- [ ] Some bug fixes and optimizations + Apply these <a href="https://github.com/TGX-Android/Telegram-X/pull/298#issuecomment-1417356837">suggestions</a>

## Screenshots
- <a href="https://github.com/TGX-Android/Telegram-X/assets/64551534/4e453115-2b00-41e7-b225-79dee67e8e7c">Resolution Selector</a>

### CODE REVIEW

**Comment by vkryl** [comment]
It seems that this PR is under development. You may convert it to draft PR (similar to how #398 is submitted), or re-submit as draft PR (in case it isn't possible to convert).

**Comment by null-nick** [comment]
Reopened here #394

**Review by xximwon — COMMENTED** [review]
Gg

**Comment by yousefimohadesee-coder** [comment]
> ## Description
> 
> Revamp increase size of photo uploads (#298) 
> 
> - [ ] Fix broken preview for photo 2560px (<a href="https://github.com/TGX-Android/Telegram-X/assets/64551534/64f27313-5835-4284-af96-33ed94ec1efb">Screenshot</a>)
> - [ ] Some bug fixes and optimizations + Apply these <a href="https://github.com/TGX-Android/Telegram-X/pull/298#issuecomment-1417356837">suggestions</a>
> 
> ## Screenshots
> - <a href="https://github.com/TGX-Android/Telegram-X/assets/64551534/4e453115-2b00-41e7-b225-79dee67e8e7c">Resolution Selector</a>

**Pull request closed without merging**
