### PR TITLE
Telegram X Android Competition: Round 2 #236 Send as 

### PR DESCRIPTION
**Pull request by mexanix**
This is a partial implementation for #236.
Unfortunately I didn't have enough time for complete implementation. However, this pull-request contains follow features:
1) sender selection button
2) popup for selection
3) an input field placeholder that reacts to the selection of the current sender

Some improvements:
improved component AvatarView for working with both avatars and icons.

Bug found:
If call SetChatMessageSender with prohibited sender (e.g. if the user does not have a premium account), then the server will still send an update object TdApi.UpdateChatMessageSender

Fixes: #236

### CODE REVIEW

**Comment by Sajilck** [comment]
[WIP Comment]

Incomplete Implementation
1) Empty space between Scheduled/BotMenu and Author Icon
2) Holding and Dragging not working on Author Icon
3) More button not working. Hence no list with complete SendAs Channels and no search available
4) Chat Avatars are not loaded in the Send as menu
5) Author icon and Chat Profile picture is merged together
6) Channel header is not shown messages
7) No protection for identity revealing activities
8) App crashes while sharing anything

**Comment by mexanix** [comment]
Thank you for your feedback! I hope to fix these bugs soon.

**Comment by vkryl** [comment]
> If call SetChatMessageSender with prohibited sender (e.g. if the user does not have a premium account), then the server will still send an update object TdApi.UpdateChatMessageSender

Just confirmed that it's not a bug, as you can achieve the same state by losing premium while having some identity that requires premium, so it should be locked on UI level. Updates are generated locally by TDLib in this case.

**Comment by vkryl** [comment]
Contest results have been announced: https://t.me/contest/311

Closing this PR to keep the list clean.

**Pull request closed without merging**
