### PR TITLE
Fix monochrome icon on One UI (Android 13+)

### LINKED ISSUE #281: Themed icon
According to this PR:

 https://github.com/TGX-Android/Telegram-X/commit/1596ce50800623dad593352dfd67158b898a1d2c

themed icon is off on Samsung devices. But in Android 13 Samsung devices get support this for third party apps. This can be seen in the screenshot. Time to activate it again.

### PR DESCRIPTION
**Pull request by nikita-toropov**
Fixes #281
screenshot

### CODE REVIEW

**Comment by dexaltat** [comment]
Finally someone did it

**Comment by dexaltat** [comment]
Finally someone did it

**Comment by BlackMesa123** [comment]
To enable back Adaptive Icon support from API 26 and above, it's better to add this meta-data flag rather than disabling that one:
```xml
<meta-data
    android:name="com.samsung.android.icon_container.feature_appicon"
    android:value="ADAPTIVEICON_SHADOW" />
```

**Comment by vkryl** [comment]
> To enable back Adaptive Icon support from API 26 and above, it's better to add this meta-data flag rather than disabling that one:
> 
> ```
> <meta-data
>     android:name="com.samsung.android.icon_container.feature_appicon"
>     android:value="ADAPTIVEICON_SHADOW" />
> ```

@BlackMesa123 Could you provide an example / comparison why you consider it's better to follow your suggestion or what benefits it provides?

**Comment by BlackMesa123** [comment]
> @BlackMesa123 Could you provide an example / comparison why you consider it's better to follow your suggestion or what benefits it provides?

The `com.samsung.android.icon_container.has_icon_container` flag was used by Samsung up to Android 10 (iirc) to disable the icon customization code for their apps since their app icons already had the squircle shape in place. Once they started to adopt Google's [adaptive icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive) (very late actually, I started seeing them in One UI 2.0 apps) this flag was not used anymore. However, Samsung apps with support for older Android versions do have both this and the additional feature meta-data flag to handle the icon customization correctly on both old UX and newer:

```xml
<!-- This one disables the icon customization for older UX (TouchWiz, Samsung Experience) -->
<meta-data android:name="com.samsung.android.icon_container.has_icon_container" android:value="true"/>
<!-- In newer UX, if the flag above is enabled and ADAPTIVEICON_SHADOW is set, icon customization is enabled again. -->
<meta-data android:name="com.samsung.android.icon_container.feature_appicon" android:value="ADAPTIVEICON_SHADOW"/>
```

This the actual code in `android.app.ApplicationPackageManager`:

```java
@Override
public boolean semShouldPackIntoIconTray(String packageName) {
    if (isNonAdaptiveIconPkg(packageName)) {
        return true;
    }

    try {
        List<String> featureList = new ArrayList<>();
        boolean ret = !mPM.getMetadataForIconTray(packageName, "com.samsung.android.icon_container.has_icon_container", mContext.getUserId(), featureList);
        if (!ret && !featureList.isEmpty()) {
            for (String feature : featureList) {
                if (FEATURE_ADAPTIVEICON_SHADOW.equals(feature)) {
                    return true;
                }
            }
        }

        if (!ret) {
            Log.i("AppIconSolution", "has_icon_container is maintained so ignore icon processing, pkg = " + packageName);
        }

        return ret;
    } catch (RemoteException e) {
        return false;
    }
}
```

**Comment by vkryl** [comment]
@BlackMesa123 thank you for the detailed explanation. It seems that both of the solutions at the moment provide absolutely the same result. On pre-A13 OneUI it's intended to keep the old non-monochrome icon, so I am considering merging this PR, at least for now, as it provides the desired result. But thank you for the hint, as maybe will have to switch to it later.

**Comment by vkryl** [comment]
@BlackMesa123 thank you for the detailed explanation. It seems that both of the solutions at the moment provide absolutely the same result. On pre-A13 OneUI it's intended to keep the old non-monochrome icon, so I am considering merging this PR, at least for now, as it provides the desired result. But thank you for the hint, as maybe will have to switch to it later.

**Review by thamer203020301 — COMMENTED** [review]
njj

**Review by biggestSmoke — COMMENTED** [review]
Delete review

**Comment by biggestSmoke** [comment]
Delete all comments

**Pull request merged**
