### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by Arseny271**

### CODE REVIEW

**Review by Tattoss99 — COMMENTED** [review]
Yy

**Review by Tattoss99 — COMMENTED** [review]
İzinsiz

**Review by bgk884 — COMMENTED** [review]
So how do I earn

**Review by cheshmrangi — COMMENTED** [review]
[text.txt](https://github.com/user-attachments/files/17447615/text.txt)

**Comment by Ramfir28** [comment]
Please

**Review by xximwon — COMMENTED** [review]
ㅇㅇ

**Review by xximwon — COMMENTED** [review]
E

**Review by Mello7cblaqbhhj — COMMENTED** [review]
gh pr checkout 734

**Review by Mello7cblaqbhhj — COMMENTED** [review]
gh pr checkout 734

**Review by Sumonnow — COMMENTED** [review]
Fine

**Review by cumcum8197 — COMMENTED** [review]
UQDefOhgYE9YOlG8ZrufgUrM-05KMmyAmIveaqzDKsSXt8el

**Review by isaacandy — COMMENTED** [review]
Looks good so far

**Review by Iezshaa0701 — COMMENTED** [review]
`app/jni/voice.c`

**Review by A-Abdurashid — COMMENTED** [review]
final

**Pull request merged**
