### PR TITLE
Custom Emoji: fixes

### PR DESCRIPTION
**Pull request by Arseny271**

### CODE REVIEW

**Comment by pypy11** [comment]
> _Không có mô tả được cung cấp._

**Comment by pypy11** [comment]
Kéo e

**Comment by Sydfg** [comment]
@Arseny271

**Comment by Sydfg** [comment]
@

**Review by Sydfg — COMMENTED** [review]
@Arseny271

**Review by azkaban21 — COMMENTED** [review]
app/src/main/java/org/thunderdog/challegram/mediaview/MediaViewController.java

**Comment by hugo555686** [comment]
> 

4073a407e76b8c34830ae719fdf9224bcb3cdad1

**Comment by hugo555686** [comment]
> 

8f217454522fdd5d31e882ed97169a91ab- [x] 140118[]()

**Review by Maaajjssj — COMMENTED** [review]
[author.txt](https://github.com/TGX-Android/Telegram-X/files/13533149/author.txt)

**Pull request merged**
