### PR TITLE
Feature: Reset password

### PR DESCRIPTION
**Pull request by CalledLuca**
## Description
I have implemented the Reset password feature. It's a clickable text that you can find when trying to access Two-Step password settings (the text is "Forgot password?"), and it allows users who have forgotten their password (**only if already logged into the account**) to reset (disable) it by confirming and waiting 7 days.

## Details
- I've followed the **style of the existing Telegram X code** as much as possible.
- For this specific feature I've followed the **behavior of other apps**.
- I've also used the same translations of other clients (I've found them on the official platform, [translations.telegram.org](https://translations.telegram.org)).
- The design is also consistent with the rest of the app.
- Before this feature, clicking on the already existing "Forgot password?" text resulted on a popup displaying [this message](https://user-images.githubusercontent.com/58666938/179085811-e3af94aa-eb0a-4a65-af86-e5fd23952714.png).

## Screenshots
Here are some screenshot of the feature:
1) [Confirmation popup](https://user-images.githubusercontent.com/58666938/179088218-883477e3-00f6-4413-aa66-4ce2c03f181b.png)
2) ["You can reset password in ..."](https://user-images.githubusercontent.com/58666938/179088445-a7b1105c-00ef-40d2-bb4a-ec5e0f78f004.png)
3) ["Cancel reset" popup](https://user-images.githubusercontent.com/58666938/179088535-d1ebfc08-97ae-4702-8f1e-da23e98ca53d.png)
4) ["Wait before making a new reset request" popup](https://user-images.githubusercontent.com/58666938/179088592-5b437762-164a-4714-8fd9-a6b7b3b3aa2c.png)
5) [Ready to reset](https://user-images.githubusercontent.com/58666938/179088677-7aa07659-f864-4a38-94cf-d581d1d596e4.png)
6) [Password reset completed](https://user-images.githubusercontent.com/58666938/179088736-68c8d1ae-875e-47e8-bac8-d19488aa3e61.png)
7) [Lost access to both recovery email & password](https://user-images.githubusercontent.com/58666938/179088768-9647867f-11dd-49f3-8dd8-ec6134441d4e.png)

I'm ready to make changes and improvements if necessary.

Hope this feature will be useful and appreciated! 🥳

### CODE REVIEW

**Comment by Sajilck** [comment]
- Duration timer is updated only after reopening the page. Timer should be reducing when in same page
- Similarly if the timer gets over when the page is open, **Forgot password?** option is only shown after reopening the page

**Comment by CalledLuca** [comment]
> * Duration timer is updated only after reopening the page. Timer should be reducing when in same page
> * Similarly if the timer gets over when the page is open, **Forgot password?** option is only shown after reopening the page

Yes, I will try to improve/fix this. Thanks for the report.

**Comment by CalledLuca** [comment]
> * Duration timer is updated only after reopening the page. Timer should be reducing when in same page
> * Similarly if the timer gets over when the page is open, **Forgot password?** option is only shown after reopening the page

Fixed.

**Comment by Mifenix333** [comment]
I was waiting for this update of telegram X.. But I can't still reset my two step password because I'm not logget in the account, Telegram X deleted my acount automaticaly when I done the last udgrade, then, It'not my falt.. I have various groups of a scholl, adm and owner..  What can I do? In november my account will do one year without acess, then, I think that it will be delete for ever..

**Comment by vkryl** [comment]
@Mifenix333 Unfortunately, if you forget your 2FA password and you do not have any devices with logged in, the only option you have remaining is to reset the account. Otherwise 2FA passwords would be meaningless, because accounts would become accessible without knowing the password. That's current Telegram policy that's not dependent on Telegram X, any other client would provide the same amount of tools for account recovery as Telegram X currently provides.

**Pull request merged**
