### PR TITLE
Telegram X Android Competition: Round 2 #237

### PR DESCRIPTION
**Pull request by fendy86i**
Your submission must contain a brief description in your GitHub pull request:
• Whether you fully accomplished the task
• What part you are most proud of
• Whether you added anything extra
• Any other info you consider useful

On improved search category, I can only fulfill the Search - 01, Search - 03, Search - 04, and partial Search - 05. I am proud for all of the work I have done because I have just learn Android Development in the beginning of October. I learn from Udemy for 1 - 2 weeks and straightly go for this contest. I am really new in this kind of contest.

I did not add anything extra feature but the transition between search - 01, search - 02 etc has been calculated perfectly even though telegram devs did not provide any kind of video to explain the transition. I did not add any new Constructor or any file whatsoever except for the icons. I only modify one single file which is the MessagesController and using all the existing available parameter, constructor, method, variable inside TGX. By doing so, it will help the judges to analyze whether my codes is right or not.

Other information useful is about the last commit in the main branch which can not build successfully. I have addressed this [issue](https://t.me/tgx_dev/8734) in TGX dev group chat. In short, here is the issue :

> I started cloning TGX from October 17th and working on the features, somehow on October 25th my Android Studio can’t emulate anyhing. I try so many things and can not find the root cause. Then I reclone again from the main repository on October 26th. Everything works well until the build process, somehow at that time I can not build the TGX on my AS. It says that it has some conflict on streaming file, but I never change anything there
> 
> Then on my AS, I try to revert to the TGX version 1567 October 25th 15:50. It worked and I can resume my work to create the feature

So for this contest, I create a PR by manually uploading 4 file drawable icons, 1 file ids, and 1 file MessagesController to my patch.

Hope my work can make significant contribution for TGX.
Thank you Telegram for setting up a great contest

Fixes: #237

### CODE REVIEW

**Comment by vkryl** [comment]
Thank you for your submission. You may find APK files containing your submission here: https://t.me/tgx_prs/317

**Comment by fendy86i** [comment]
thanks, if I want to fix the bugs from my submission or complete some missing features, are we allowed to do it start from now?

**Comment by Sajilck** [comment]
Telegram X 0.25.1.1571-arm64-v8a (6ee55b9d)
PRs: #254 (f3bace21)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: Pie (28)
Device: OnePlus OnePlus ONEPLUS A3003 (ONEPLUS A3003_28_191104)
Screen: 1794x1080 (density: 2.625, fps: 60.000004)
Build: `OnePlus/OnePlus3/OnePlus3T:9/PKQ1.181203.001/1911042108:user/release-keys`
Package: com.contest.fendy86i.pr_254
Installer: io.github.muntashirakon.AppManager
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

1) Search message from user not available, clicking on button does nothing
2) Number of results not available only with filter and no text in search query
3) Up/down arrow not available only with filter and no text in search query
4) Message from X screen opens old screen only
5) Scroll Down arrow button is invisible but counter is not hidden while in search mode

6) Search query not highlighted
7) Search results only mode not available, button (after counter) does nothing
8) when a message is selected on search mode, search mode exists but the position doesn't scroll to selected message.
Expected: Scroll to selected message/don't exit search mode, allow multiple selection
9) Selected filter icon color is not matching as per design
----
Comment completed

**Comment by fendy86i** [comment]
Hi !
Thanks for the feedback. I have just fix the issue #5 . I will submit the commit if I have fix several more issues.

**Comment by vkryl** [comment]
Contest results have been announced: https://t.me/contest/311

Closing this PR to keep the list clean.

**Pull request closed without merging**
