### PR TITLE
Eager Cat's reactions contest entry (#154)

### PR DESCRIPTION
**Pull request by grishka**
The task is fully completed but there are some things I'm not sure about. Here are some additional comments:

* **The animations use a custom lottie renderer built on top of the existing native library.** This renderer is asynchronous and multi-threaded and thus takes advantage of multi-core CPUs in modern phones. Complex animations, or multiple animations, don't slow down the UI thread — they instead just skip frames. Existing sticker/emoji rendering code is unaffected.
* **The animations get preloaded upon launch.** This is needed so they can start immediately when needed, but I'm not sure what's the resource cost of keeping all those rlottie files open. You'd probably run out of RAM if there are too many available reactions. There's definitely some room for optimization.
* Since there is no bubble shape change animations already in the app, **the bubble shape is not animated when the button layout changes**. But the buttons themselves **are** animated.
* Speaking of reaction buttons, most of the code for those was copied from my previous (late 2021) contest entry and adapted to TGX. I had to change MessageView to be a ViewGroup because I'm not having any of this draw-everything-manually-on-canvas stuff, sorry.
* Real-time reaction updates sometimes simply don't arrive. This feels like a tdlib bug to me. It sometimes fixes itself eventually, or you can restart the app.
* The swipe reactions only work in places where you can reply to messages — so not in channels where you are not an admin, for example.
* There's code that suggests swipes can be done in both directions (left to right to forward a message), but I didn't have time to figure out how to trigger this behavior. There's a non-zero possibility I broke it.
* Premium reactions in settings are displayed on non-premium accounts. You can't save them as available in chats (which is a tdlib or backend bug — you *should* be able to, I'm able to do it on TDesktop as a non-premium user) and you can't add them even when they've already been added to a message by a premium user. There are valid use cases for non-premium users seeing premium reactions, so I didn't hide them. This is a UX question more than a technical one.

p.s. *eager meow*

### CODE REVIEW

**Comment by vkryl** [comment]
Thank you for your submission and detailed explanation. I wanted to reply to the specific part of it:

> Since there is no bubble shape change animations already in the app, the bubble shape is not animated when the button layout changes. But the buttons themselves are animated.

While this is mostly true, there are few cases when bubble properly animates: you can see how bubble animates when editing captions of files or deleting a file in a set of files sent as group.

Could you also please sync with `main` (421962e) to resolve the conflict once you feel the work is finished? Since it's just about `strings.xml`, it's OK to sync after the deadline (given the commit will address only the conflict).

**Comment by grishka** [comment]
Are there? A crash log would be helpful (though the deadline has already passed)

**Comment by grishka** [comment]
Ah, you mean in settings -> themes & chats -> wallpaper? Indeed it does ¯\\\_(ツ)_/¯
The idea that not only actual chats but also things like this may also use `MessagesController` never crossed my mind. At least recent actions don't crash.

**Comment by null-nick** [comment]
Trying this build I encountered the following bugs/crashes:

⁃ If one or more quick reactions are set, from a second profile, they will not be enabled because they are already active on the main profile.

⁃ It could happen that sending a big reaction Tgx crashes (Crash that happens every now and then, unfortunately I couldn't catch the crash error).

⁃ If quick reactions are turned off, the chosen emojis remain marked as active.

⁃ When you send a reaction to a message the menu of the reactor will not appear at the moment, you will have to go out and go back into the chat to make it appear.

⁃ By setting a quick reaction, and performing the gesture to go back, the reaction animation will appear at the top left.

⁃ Turning on/off big reactions remain active, even if turned off by settings.

https://user-images.githubusercontent.com/64551534/177103013-40658137-e1ec-45d1-8e34-d2258489d6de.MOV

**Comment by Sajilck** [comment]
- Upto 3 quick reaction can be enabled, but there is no way to specify the order in settings. First in the list always taken preference.
- Changing quick reaction from other client is not synced in the app.
- Disabling swipe to reply disables quick reaction
- Swipping first time on all reacted user list to specific reaction user list is not smooth
- "reactions panel is shown for ""Calls"" entry in the chat, which is not supposed to show
- reactions are not visible under video messages.
- Crash while trying to react to video message
- Reaction panel is visible on **More…** context menu, which should not be visible
- Reaction is visible on Sponsored Message, which should not be visible
- Reaction counter has not become blue for reacted message in small reaction mode

Device Details:
Android Pie(28)
OnePlus ONEPLUS A3003 (ONEPLUS A3003_28_191104)

**Comment by grishka** [comment]
> Upto 3 quick reaction can be enabled, but there is no way to specify the order in settings. First in the list always taken preference.

There was nothing in the contest task about this.

> Changing quick reaction from other client is not synced in the app.

Of course it isn't?! It's a 100% client-side setting.

> Disabling swipe to reply disables quick reaction

That's intentional.

> Swipping first time on all reacted user list to specific reaction user list is not smooth

That's a bug in ViewPager, I suppose.

> "reactions panel is shown for ""Calls"" entry in the chat, which is not supposed to show

Yes

> reactions are not visible under video messages.

Didn't test that and tbh forgot that video messages are a thing

> Crash while trying to react to video message

Whatever, the deadline was 2 days ago

> Reaction panel is visible on More… context menu, which should not be visible
> Reaction is visible on Sponsored Message, which should not be visible

¯\\\_(ツ)_/¯

> Reaction counter has not become blue for reacted message in small reaction mode

I may have forgotten about this part because of how overwhelming the number of these tiny little details was.

**Comment by null-nick** [comment]
Reacting to a message in a group with more than 50 members, the reaction counter appears only by exiting and re-entering the chat. 

https://user-images.githubusercontent.com/64551534/179099867-f48ee81e-60eb-488d-a208-e6c08dd748cb.mp4

**Comment by vkryl** [comment]
Thank you very much for the high-quality submission. Closing this PR as #185 got merged into the `main` branch. Choosing between your submission and #185 was difficult, as your work had an advantage of better reactions animations playback on high-end devices and the curve of the reaction's "flight" from the menu, however, #185 implemented all steps of the animation fully, including the bubble changes, therefore it was selected.

Described the key reasons how PR for production was selected also here: https://github.com/TGX-Android/Telegram-X/issues/154#issuecomment-1209453218

Latest commit of this PR is available here: https://t.me/tgx_prs/297
Announcement will be published in https://t.me/contest soon.

**Comment by tekeyew97** [comment]
Nice

**Pull request closed without merging**
