### PR TITLE
Chat Folders: Fixes

### PR DESCRIPTION
**Pull request by nikita-toropov**

### CODE REVIEW

**Comment by brent85** [comment]
app/src/main/java/org/thunderdog/challegram/component/user/BubbleView.java

**Comment by brent85** [comment]
Brent Thomas <thomasfamily8583@gmail.com>

**Comment by brent85** [comment]
echo "# Brent-Thomas-all-websites-records" >> README.md
git init
git add README.md
git commit -m "first commit"
git branch -M main
git remote add origin https://github.com/brent85/Brent-Thomas-all-websites-records.git
git push -u origin main

**Comment by cumcum8197** [comment]
43400a3dc4153678c4e6e545183390156106dfb1

**Pull request merged**
