### PR TITLE
Feature: Delete (single) recent sticker

### PR DESCRIPTION
**Pull request by CalledLuca**
## Description
I have implemented a button that allows to delete a **single** sticker from the Recently used panel.
Until now, the only way to delete recent stickers was long-pressing the clock icon in the stickers panel, but there was no way to delete them individually.

## Details
- I've followed the **style of the existing Telegram X code**.
- The design is consistent with the rest of the app.
- You can access this button by long-pressing on a sticker from the Recently used panel.

## Notes
- I've removed `ignoreNextRecentsUpdate` ([see this commit](https://github.com/TGX-Android/Telegram-X/commit/9736f2b3b4728aa0dabc0d9e2dff97f94ce0a595)) and related method and variables because it was the cause of various bugs (and it was also preventing this feature to work correctly in specific cases). These changes fix various bugs, but as @vkryl told me some improvements will be needed to cover some edge-case problems.

## Screenshot
1) [The button itself](https://user-images.githubusercontent.com/58666938/179126493-15518c11-efcd-4b45-b0d9-8b314e3d3897.png)

I'm ready to make changes and improvements if necessary.

### CODE REVIEW

**Comment by Sajilck** [comment]
For me it looks like the icon has to be changed, what about reusing the one used for "Clear recent stickers" or "Delete pack" ?

**Comment by CalledLuca** [comment]
> For me it looks like the icon has to be changed, what about reusing the one used for "Clear recent stickers" or "Delete pack" ?

Thanks for the suggestion! I've asked to the designer in the group: https://t.me/tgx_dev/2629.

As you can read, he said that the current icon is more self-explanatory for this specific action than the other ones (and I agree with him).
Do you agree too? If you suggested to change it to avoid adding a new icon, I don't think this will have significant impact.

**Comment by CalledLuca** [comment]
> The button to delete a recent sticker is only displayed if English is the system language. Screenshots: [English](https://user-images.githubusercontent.com/109213781/179260479-4b382fe0-b23f-4993-82f1-0cc312565432.png), [Russian](https://user-images.githubusercontent.com/109213781/179261110-2046eb87-9ee6-4ac6-b401-f22c6ce3b4a1.png), [German](https://user-images.githubusercontent.com/109213781/179261241-dc9d4993-a845-49d9-b300-a2cb94d49114.png) (in some cases you can see a few pixels on the right).

Thanks for report! I'll fix this soon.

**Comment by CalledLuca** [comment]
> The button to delete a recent sticker is only displayed if English is the system language. Screenshots: [English](https://user-images.githubusercontent.com/109213781/179260479-4b382fe0-b23f-4993-82f1-0cc312565432.png), [Russian](https://user-images.githubusercontent.com/109213781/179261110-2046eb87-9ee6-4ac6-b401-f22c6ce3b4a1.png), [German](https://user-images.githubusercontent.com/109213781/179261241-dc9d4993-a845-49d9-b300-a2cb94d49114.png) (in some cases you can see a few pixels on the right).

This was fixed with this commit: https://github.com/TGX-Android/Telegram-X/commit/87f27094319c4eda08b44fabc1d6344faa8a0d59. You will be able to test it in the next build that will be published in [@tgx_prs](https://t.me/tgx_prs).
Note that additional fixes for smaller devices and longer strings will be made.

Thanks for the report!

**Pull request merged**
