### PR TITLE
Telegram X Contest - Improved Search #237

### PR DESCRIPTION
**Pull request by Arseny271**
All features are implemented.

Special attention has been paid to this [problem](https://t.me/tgx_dev/7325). The `MessagesSearchManagerMiddleware` class mediates between existing code and tdlib. Thus, the code of the `MessagesManager` and `MessagesSearchManager` classes requires minimal changes, but there is support for double filters at the same time. If support for double filters appears at the telegram backend, the class can be removed without consequences

Addition: `MessagesSearchManagerMiddleware` supports filter by sender in user chats and secret chats

Fixes: #237

### CODE REVIEW

**Comment by vkryl** [comment]
Thank you for your submission!

While the main evaluation will be made during this week, I privately sneak peaked into your work and wanted to leave a few suggestions for improvements, mainly in "messages from X" button flow.

1. When pressing "messages from X" in a chat, it could remember the message that was used to enter the search to anchor scroll position to it instead of the first four found result.
2. When pressing "messages from X" from outside the chat (e.g. from chat members list), `MessagesController` could be in read-only mode, and pressing back button should take back to the previous screen, not exiting the search UI.
3. After pressing "Messages from X" inside the chat, scrolling, and returning back to the chat, current scroll behaviour is weird and sometimes highlights several messages at once. The best solution seems to be to fully restoring the scroll position saved upon entering the "only found messages" mode.
4. When highlighting search query in messages with web page (or whichever other place that has several search fields), it should keep the results of `Hightlight` that consume the biggest number of characters of the input query (in the screenshot below it would allow dropping the highlighting of "re" in the web page title).

**Comment by Sajilck** [comment]
Telegram X 0.25.1.1571-arm64-v8a (6ee55b9d)
PRs: #246 (0b81a35f)
TDLib: 1.8.7 (tdlib/td@76f5f33)
Android: Pie (28)
Device: OnePlus OnePlus ONEPLUS A3003 (ONEPLUS A3003_28_191104)
Screen: 1794x1080 (density: 2.625, fps: 60.000004)
Build: `OnePlus/OnePlus3/OnePlus3T:9/PKQ1.181203.001/1911042108:user/release-keys`
Package: com.contest.arseny271.pr_246
Installer: io.github.muntashirakon.AppManager
Fingerprint: `66:46:21:34:34:5a:6a:da:c3:c1:d5:ae:a9:ce:f0:42:1b:7c:ab:68`

1) Messages from X screen from members list initially shows the chat with current position messages before showing loading messages screen.
On official beta, it takes directly to loading messages screen and then to results
https://user-images.githubusercontent.com/25002879/198975868-d43a58f8-7089-4a41-a5af-5f57c11fdaf5.mp4

2)

**Comment by vkryl** [comment]
You may find APK files containing your submission here: https://t.me/tgx_prs/335

**Comment by Arseny271** [comment]
> 2. Wrong search result counter with filters. Number of results getting changed while moving through results

When two filters are used, it is impossible to know the exact number of results. The counter will decrease as messages are loaded until it reaches the correct value.



> 5. With available search results, when moving to a different date, result on specific date is highlighted but counter doesn't change position. Up/down arrow brings back to old position.
Expected: counter moves based on the new result. Up/down arrow should be showing next/prev result of the newly highlighted message

Good idea, but sometimes it is problematic to find out the message index for the correct display of the counter, for example, if the messages are far in the past and there are many messages found.

**Comment by Whitebrim** [comment]
Message selection is not working in search mode ([0b81a35](https://github.com/TGX-Android/Telegram-X/pull/246/commits/0b81a35f1791ecb8c6abe0e5fed6032c207fa3f7)).
Is it intentional? I use search for forwarding multiple messages and I'm tired of exiting search mode to select messages.
Can you please exit search mode automatically and enter message selecting mode if user tap and hold message?

Sorry if this feedback is late or not in the proper thread~

**Comment by dexaltat** [comment]
It would be great to add the sorting  by "Links"

**Pull request merged**
